version: '3.3'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5433:5432"

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"]

volumes:
  postgres_data:
